#############################################################################
# Generated by PAGE version 8.1rcc
#  in conjunction with Tcl version 8.6
#  Feb 14, 2025 03:10:08 AM CST  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
    system_shutdown_png "./graphics/system-shutdown.png" 
    information_png "./graphics/information.png" 
    question_png "./graphics/question.png" 
    computergeek_transback_175x247_png "./graphics/computergeek transback.175x247.png" 
}
vTcl:create_project_images $image_list   ;# In image.tcl

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Absolute
set vTcl(mode) Absolute
set vTcl(project_theme) default



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 547x559+726+571
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4465 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Enhanced Listbox Demo"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::frame "$top.tFr50" \
        -borderwidth 2 -relief groove -width 265 -height 535 -style "" 
    vTcl:DefineAlias "$top.tFr50" "TFrame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.tFr50
    ttk::frame "$site_3_0.tFr51" \
        -borderwidth 2 -relief groove -width 255 -height 75 -style "" 
    vTcl:DefineAlias "$site_3_0.tFr51" "TFrameMarquee" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.tFr51
    ttk::label "$site_4_0.tLa52" \
        -font "TkDefaultFont" -relief sunken -anchor center -justify center \
        -text "The Enhanced
Listbox" -underline -1 -width 222 -compound left \
        -state normal -style "" 
    vTcl:DefineAlias "$site_4_0.tLa52" "TLabel1" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.tLa52 \
        -in $site_4_0 -x 17 -y 13 -width 222 -relwidth 0 -height 49 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::frame "$site_3_0.tFr53" \
        -borderwidth 2 -relief groove -width 245 -height 455 -style "" 
    vTcl:DefineAlias "$site_3_0.tFr53" "TFrameSLBHolder" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.tFr53
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd "$site_4_0.scr54" \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 75 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 125 
    vTcl:DefineAlias "$site_4_0.scr54" "Scrolledlistbox1" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr54.01 configure -background white \
        -cursor xterm \
        -exportselection 0 \
        -font TkFixedFont \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #d9d9d9 \
        -selectforeground black \
        -width 10
    place $site_4_0.scr54 \
        -in $site_4_0 -x 1 -y 1 -width 256 -relwidth 0 -height 449 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tFr51 \
        -in $site_3_0 -x 2 -y 2 -width 255 -relwidth 0 -height 75 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tFr53 \
        -in $site_3_0 -x 2 -y 78 -width 261 -relwidth 0 -height 455 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::button "$top.tBu49" \
        -command "on_btnExit" -default normal -takefocus ttk::takefocus \
        -underline -1 -image system_shutdown_png -compound left -state normal \
        -style "" 
    vTcl:DefineAlias "$top.tBu49" "btnExit" vTcl:WidgetProc "Toplevel1" 1
    ttk::button "$top.tBu50" \
        -command "on_btnAbout" -default normal -takefocus ttk::takefocus \
        -underline -1 -image information_png -compound left -state normal \
        -style "" 
    vTcl:DefineAlias "$top.tBu50" "btnAbout" vTcl:WidgetProc "Toplevel1" 1
    bind $top.tBu50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Show About Information}
    }
    ttk::button "$top.tBu51" \
        -command "on_btnHelp" -default normal -underline -1 \
        -image question_png -compound left -state normal -style "" 
    vTcl:DefineAlias "$top.tBu51" "btnHelp" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tFr50 \
        -in $top -x 10 -y 10 -width 265 -relwidth 0 -height 535 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 490 -y 10 -width 43 -relwidth 0 -anchor nw \
        -bordermode ignore 
    place $top.tBu50 \
        -in $top -x 388 -y 10 -width 43 -relwidth 0 -height 43 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu51 \
        -in $top -x 440 -y 10 -width 43 -relwidth 0 -anchor nw \
        -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -relief flat -background #d9d9d9 -container 0 \
        -height 0 -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 547x559+736+579
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4465 1410
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "About"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "About" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    ttk::label "$top.tLa51" \
        -font "TkDefaultFont" -relief flat -anchor w -justify left \
        -underline -1 -image computergeek_transback_175x247_png \
        -compound left -state normal -style "" 
    vTcl:DefineAlias "$top.tLa51" "TLabel2" vTcl:WidgetProc "About" 1
    message "$top.mes52" \
        -anchor center -aspect 150 -background #d9d9d9 -borderwidth 3 \
        -cursor fleur -font "TkDefaultFont" -foreground black \
        -highlightbackground #d9d9d9 -highlightcolor #000000 \
        -highlightthickness 0 -justify center -padx 1 -pady 1 -relief ridge \
        -takefocus 0 -text "Message" -textvariable "MessageData" -width 332 
    vTcl:DefineAlias "$top.mes52" "Message1" vTcl:WidgetProc "About" 1
    set MessageData {Message}
    ttk::button "$top.tBu49" \
        -command "on_btnAboutDismiss" -default normal \
        -takefocus ttk::takefocus -text "Dismiss" -underline -1 -width 133 \
        -compound left -state normal -style "" 
    vTcl:DefineAlias "$top.tBu49" "btnAboutDismiss" vTcl:WidgetProc "About" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tLa51 \
        -in $top -x 350 -y 155 -anchor nw -bordermode ignore 
    place $top.mes52 \
        -in $top -x 7 -y 24 -width 332 -relwidth 0 -height 511 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tBu49 \
        -in $top -x 380 -y 500 -width 133 -relwidth 0 -height 28 -relheight 0 \
        -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}

